const data = {
  organizationId: 1,
  country: 'Spain',
  visaType: 'Tourist',
  plannedTravelDate: '2024-01-01T00:00:00',
  adminName: 'Farit',
  adminMessageTime: '2023-01-01T00:00:00',
  adminMessage:
    'dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf dsafdsaf',
  customers: [
    {
      name: 'ferit',
      email: 'feritzcan93@gmail.com',
      surname: 'ozcan',
      phone: '5325596676',
      taxType: 'All',
      date: '2024-01-01T00:00:00',
      applicationStatus: [1, 2],
      files: [
        {
          fileName: 'a1.jpg',
          fileUrl: null,
          fileStatus: 0,
          requiredFileDetails: {
            index: 0,
            fileName: 'Şengen Vize Başvuru Formu',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description:
              'Lütfen shengen vize başvuıru formunu doldurduktan sonra indiriniz.\\n sadasdsadsadsaasd',
            uploadRequired: false,
            status: 'Approved',
            id: 1,
          },
          id: 7,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 3,
          requiredFileDetails: {
            index: 0,
            fileName: 'Uçak Biletleri',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description: 'DSAADSDASDSADSAAAADSASDSDA',
            uploadRequired: true,
            status: 'Belge onay bekliyor',
            id: 2,
          },
          id: 8,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 2,
          requiredFileDetails: {
            index: 0,
            fileName: 'Otel Biletleri',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description:
              'Lütfen shengen vize başvuıru formunu doldurduktan sonra indiriniz.\\n sadasdsadsadsaasd',
            uploadRequired: true,
            status: 'Not Approved',
            id: 3,
          },
          id: 9,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 1,
          requiredFileDetails: {
            index: 0,
            fileName: 'Only Student',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description: 'adsadsdsasdas',
            uploadRequired: true,
            status: 'Not Uploaded',
            id: 4,
          },
          id: 10,
        },
      ],
      id: 5,
    },
    {
      name: 'Ali',
      email: 'Ali@gmail.com',
      surname: 'Khan',
      phone: '111111111',
      taxType: 'Student',
      applicationStatus: [1, 2, 3, 4],
      files: [
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 0,
          requiredFileDetails: {
            index: 0,
            fileName: 'Şengen Vize Başvuru Formu',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description:
              'Lütfen shengen vize başvuıru formunu doldurduktan sonra indiriniz.\\n sadasdsadsadsaasd',
            uploadRequired: false,
            id: 1,
          },
          id: 7,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 0,
          requiredFileDetails: {
            index: 0,
            fileName: 'Uçak Biletleri',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description: 'DSAADSDASDSADSAAAADSASDSDA',
            uploadRequired: false,
            id: 2,
          },
          id: 8,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 2,
          requiredFileDetails: {
            index: 0,
            fileName: 'Otel Biletleri',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description:
              'Lütfen shengen vize başvuıru formunu doldurduktan sonra indiriniz.\\n sadasdsadsadsaasd',
            uploadRequired: true,
            id: 3,
          },
          id: 9,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 1,
          requiredFileDetails: {
            index: 0,
            fileName: 'Only Student',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description: 'adsadsdsasdas',
            uploadRequired: true,
            id: 4,
          },
          id: 10,
        },
      ],
      id: 5,
    },
    {
      name: 'Awais',
      email: 'awaisoffwork@gmail.com',
      surname: 'Ahmed',
      phone: '222222222',
      taxType: 'Retired',
      applicationStatus: [1],
      files: [
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 0,
          requiredFileDetails: {
            index: 0,
            fileName: 'Şengen Vize Başvuru Formu',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description:
              'Lütfen shengen vize başvuıru formunu doldurduktan sonra indiriniz.\\n sadasdsadsadsaasd',
            uploadRequired: false,
            id: 1,
          },
          id: 7,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 0,
          requiredFileDetails: {
            index: 0,
            fileName: 'Uçak Biletleri',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description: 'DSAADSDASDSADSAAAADSASDSDA',
            uploadRequired: true,
            id: 2,
          },
          id: 8,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 2,
          requiredFileDetails: {
            index: 0,
            fileName: 'Otel Biletleri',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description:
              'Lütfen shengen vize başvuıru formunu doldurduktan sonra indiriniz.\\n sadasdsadsadsaasd',
            uploadRequired: true,
            id: 3,
          },
          id: 9,
        },
        {
          fileName: null,
          fileUrl: null,
          fileStatus: 1,
          requiredFileDetails: {
            index: 0,
            fileName: 'Only Student',
            helpLink: 'https://www.google.com',
            exampleDocumentLink: null,
            description: 'adsadsdsasdas',
            uploadRequired: true,
            id: 4,
          },
          id: 10,
        },
      ],
      id: 5,
    },
  ],
  id: 8,
};

export default data;
